config/routes.rb
# frozen_string_literal: true

Mr519Gen::Engine.routes.draw do
  resources :campos, only: [], param: :index do
    member do
      delete "(:id)", to: "campos#destroy", as: "eliminar"
      post "/", to: "campos#create", as: "crear"
    end
  end

  get "/encuestaexterna/:adurl", to: "encuestaspersona#externa",
    as: :encuestaexterna

  resources :encuestaspersona, path_names: { new: "nueva", edit: "edita" }

  resources :encuestasusuario, path_names: { new: "nueva", edit: "edita" }
  get "/encuestasusuario/resultados/:encuestausuario_id" =>
    "encuestasusuario#resultados",
    as: :resultadosencuestausuario
  get "/encuestasusuario/creartodousuario/:encuestausuario_id" =>
  "encuestasusuario#creartodousuario",
    as: :creartodousuario

  resources :formularios, path_names: { new: "nuevo", edit: "edita" }
  get "/formularios/copia/:formulario_id", to: "formularios#copia",
    as: :copia_formulario

  resources :opcionescs, only: [], param: :index do
    member do
      delete "(:id)", to: "opcionescs#destroy", as: "eliminar"
      post "/", to: "opcionescs#create", as: "crear"
    end
  end

  resources :planesencuesta,
    path_names: { new: "nuevo", edit: "edita" }

end

app/models/mr519_gen/ability.rb
# frozen_string_literal: true

module Mr519Gen
  class Ability < Msip::Ability
    BASICAS_PROPIAS = []

    def tablasbasicas
      Msip::Ability::BASICAS_PROPIAS +
        Mr519Gen::Ability::BASICAS_PROPIAS
    end

    NOBASICAS_INDSEQID = [
      ["Mr519Gen", "campo"],
      ["Mr519Gen", "encuestapersona"],
      ["Mr519Gen", "encuestausuario"],
      ["Mr519Gen", "formulario"],
      ["Mr519Gen", "planencuesta"],
      ["Mr519Gen", "respuestafor"],
      ["Mr519Gen", "valorcampo"],
    ]

    # Tablas no básicas pero que tienen índice *_seq_id
    def nobasicas_indice_seq_con_id
      Msip::Ability::NOBASICAS_INDSEQID +
        NOBASICAS_INDSEQID
    end

    # Se definen habilidades con cancancan
    # Util en motores y aplicaciones de prueba
    # En aplicaciones es mejor escribir completo el modelo de autorización
    # para facilitar su análisis y evitar cambios inesperados al actualizar
    # motores
    # @usuario Usuario que hace petición
    def initialize_mr519_gen(usuario = nil)
      # El primer argumento para can es la acción a la que se da permiso,
      # el segundo es el recurso sobre el que puede realizar la acción,
      # el tercero opcional es un diccionario de condiciones para filtrar
      # más (e.g :publicado => true).
      #
      # El primer argumento puede ser :manage para indicar toda acción,
      # o grupos de acciones como :read (incluye :show e :index),
      # :create, :update y :destroy.
      #
      # Si como segundo argumento usa :all se aplica a todo recurso,
      # o puede ser una clase.
      #
      # Detalles en el wiki de cancan:
      #   https://github.com/ryanb/cancan/wiki/Defining-Abilities

      initialize_msip(usuario)
      return unless usuario && usuario.rol

      case usuario.rol
      when Ability::ROLANALI
        can(:read, [Mr519Gen::Encuestausuario, Mr519Gen::Encuestapersona])
        can(
          [:edit, :update],
          Mr519Gen::Encuestausuario.where(usuario_id: usuario.id),
        )

      when Ability::ROLADMIN
        can(:manage, [
          Mr519Gen::Encuestausuario,
          Mr519Gen::Encuestapersona,
          Mr519Gen::Formulario,
          Mr519Gen::Campo,
          Mr519Gen::Opcioncs,
          Mr519Gen::Planencuesta,
        ])
      end
    end # def initialize_jn316_gen
  end # class
end # module

app/models/mr519_gen/application_record.rb
# frozen_string_literal: true

module Mr519Gen
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/mr519_gen/campo.rb
# frozen_string_literal: true

require "mr519_gen/concerns/models/campo"

module Mr519Gen
  # Un campo en un formulario, puede ser de diversos tipos (entero, fecha,
  # cadena, selección sencilla, selección múltiple, etc.)
  class Campo < ActiveRecord::Base
    include Mr519Gen::Concerns::Models::Campo
  end
end

app/models/mr519_gen/encuestapersona.rb
# frozen_string_literal: true

require "mr519_gen/concerns/models/encuestapersona"

module Mr519Gen
  # Encuesta a una persona externa (i.e que no tiene cuenta en el sistema de
  # información)
  class Encuestapersona < ActiveRecord::Base
    include Mr519Gen::Concerns::Models::Encuestapersona
  end
end

app/models/mr519_gen/encuestausuario.rb
# frozen_string_literal: true

require "mr519_gen/concerns/models/encuestausuario"

module Mr519Gen
  # Encuesta a un usuario del sistema de información
  class Encuestausuario < ActiveRecord::Base
    include Mr519Gen::Concerns::Models::Encuestausuario
  end
end

app/models/mr519_gen/formulario.rb
# frozen_string_literal: true

require "mr519_gen/concerns/models/formulario"

module Mr519Gen
  # Modela un formulario con campos definibles por el usuario
  class Formulario < ActiveRecord::Base
    include Mr519Gen::Concerns::Models::Formulario
  end
end

app/models/mr519_gen/modelo.rb
# frozen_string_literal: true

module Mr519Gen
  # Extiende Msip::Modelo para facilitar presentar
  # información de formularios
  module Modelo
    extend ActiveSupport::Concern

    included do
      include Msip::Modelo

      def presenta_gen_mr519(atr)
        if atr.to_s.include?(".")
          pa = atr.split(".")
          f = Mr519Gen::Formulario
            .where(nombreinterno: pa[0])
          if f.count == 1
            fr = f.take
            if respuestafor &&
                respuestafor.where(
                  formulario_id: fr.id,
                ).count == 1
              rf = respuestafor.find_by(
                formulario_id: fr.id,
              )
              ca = fr.campo.where(nombreinterno: pa[1])
              return "No hay campo '#{pa[1]}' en formulario '#{pa[0]}'" unless ca.count == 1

              vc = rf.valorcampo.where(
                campo_id: ca.take.id,
              )
              if vc.count == 1
                vc.take.presenta_valor(false)
              elsif vc.count == 0
                ""
              else
                "Hay más de un valor para campo '#{pa[1]}' de formulario '#{pa[0]}'"
              end

            else
              puts "No hay respuesta para formulario '#{pa[0]}"
              ""
            end
          elsif f.count == 0
            "No hay formulario '#{pa[0]}'"
          else
            "Varios formularios '#{pa[0]}'"
          end

        else
          presenta_gen_msip(atr)
        end
      end

      def presenta_gen(atr)
        presenta_gen_mr519(atr)
      end
    end
  end
end

app/models/mr519_gen/opcioncs.rb
# frozen_string_literal: true

require "mr519_gen/concerns/models/opcioncs"

module Mr519Gen
  # Opción en un campo de selección
  class Opcioncs < ActiveRecord::Base
    include Mr519Gen::Concerns::Models::Opcioncs
  end
end

app/models/mr519_gen/planencuesta.rb
# frozen_string_literal: true

require "mr519_gen/concerns/models/planencuesta"

module Mr519Gen
  # Plan para efectuar una encuesta (e.g. fechas de aplicación, formulario)
  class Planencuesta < ActiveRecord::Base
    include Mr519Gen::Concerns::Models::Planencuesta
  end
end

app/models/mr519_gen/respuestafor.rb
# frozen_string_literal: true

require "mr519_gen/concerns/models/respuestafor"

module Mr519Gen
  # Respuesta a un formulario, relaciona los campos del formulario con
  # los valores que una persona diligencia.
  class Respuestafor < ActiveRecord::Base
    include Mr519Gen::Concerns::Models::Respuestafor
  end
end

app/models/mr519_gen/valorcampo.rb
# frozen_string_literal: true

require "mr519_gen/concerns/models/valorcampo"

module Mr519Gen
  # Valor que un usuario/persona diligencia en un campo de un formulario
  class Valorcampo < ActiveRecord::Base
    include Mr519Gen::Concerns::Models::Valorcampo
  end
end

app/controllers/mr519_gen/application_controller.rb
# frozen_string_literal: true

module Mr519Gen
  class ApplicationController < ActionController::Base
    # Sin autorizacion porque es usada por otras
    protect_from_forgery with: :exception
  end
end

app/controllers/mr519_gen/campos_controller.rb
# frozen_string_literal: true

require "mr519_gen/concerns/controllers/campos_controller"

module Mr519Gen
  class CamposController < Msip::ModelosController
    before_action :preparar_campo_formulario
    load_and_authorize_resource class: Mr519Gen::Campo
    include Mr519Gen::Concerns::Controllers::CamposController
  end
end

app/controllers/mr519_gen/encuestaspersona_controller.rb
# frozen_string_literal: true

require "mr519_gen/concerns/controllers/encuestaspersona_controller"

module Mr519Gen
  class EncuestaspersonaController < Msip::ModelosController
    load_and_authorize_resource class: Mr519Gen::Encuestapersona
    before_action :set_encuestapersona,
      only: [:show, :edit, :update, :destroy]
    include Mr519Gen::Concerns::Controllers::EncuestaspersonaController
  end
end

app/controllers/mr519_gen/encuestasusuario_controller.rb
# frozen_string_literal: true

require "mr519_gen/concerns/controllers/encuestasusuario_controller"

module Mr519Gen
  class EncuestasusuarioController < Msip::ModelosController
    load_and_authorize_resource class: Mr519Gen::Encuestausuario
    before_action :set_encuestausuario,
      only: [:show, :edit, :update, :destroy]
    include Mr519Gen::Concerns::Controllers::EncuestasusuarioController
  end
end

app/controllers/mr519_gen/formularios_controller.rb
# frozen_string_literal: true

require_dependency "mr519_gen/concerns/controllers/formularios_controller"

module Mr519Gen
  class FormulariosController < Msip::ModelosController
    load_and_authorize_resource class: Mr519Gen::Formulario
    before_action :set_formulario,
      only: [:show, :edit, :update, :destroy]

    include Mr519Gen::Concerns::Controllers::FormulariosController
  end
end

app/controllers/mr519_gen/opcionescs_controller.rb
# frozen_string_literal: true

require_dependency "mr519_gen/concerns/controllers/opcionescs_controller"

module Mr519Gen
  class OpcionescsController < Msip::ModelosController
    before_action :preparar_opcion_campo_formulario
    load_and_authorize_resource class: Mr519Gen::Opcioncs
    include Mr519Gen::Concerns::Controllers::OpcionescsController
  end
end

app/controllers/mr519_gen/planesencuesta_controller.rb
# frozen_string_literal: true

require_dependency "mr519_gen/concerns/controllers/planesencuesta_controller"

module Mr519Gen
  class PlanesencuestaController < Msip::ModelosController
    load_and_authorize_resource class: Mr519Gen::Planencuesta
    include Mr519Gen::Concerns::Controllers::PlanesencuestaController
  end
end

app/helpers/mr519_gen/application_helper.rb
# frozen_string_literal: true

module Mr519Gen
  module ApplicationHelper
    include Msip::PaginacionAjaxHelper

    TEXTO = 1
    TEXTOLARGO = 2
    ENTERO = 3
    BOOLEANO = 4
    FLOTANTE = 5
    SELECCIONMULTIPLE = 10
    SELECCIONSIMPLE = 11
    FECHA = 12
    PRESENTATEXTO = 13
    SMTABLABASICA = 14
    SSTABLABASICA = 15

    TIPOS_CAMPO = [
      ["Booleano", BOOLEANO],
      ["Entero", ENTERO],
      ["Fecha", FECHA],
      ["Flotante", FLOTANTE],
      ["Respuesta abierta", TEXTO],
      ["Respuesta abierta larga", TEXTOLARGO],
      ["Presentar texto", PRESENTATEXTO],
      ["Selección Múltiple", SELECCIONMULTIPLE],
      ["Selección Múltiple con Tabla Básica", SMTABLABASICA],
      ["Selección Simple", SELECCIONSIMPLE],
      ["Selección Simple con Tabla Básica", SSTABLABASICA],
    ]

    # La misma constante debe estar en app/javascript/motor.coffee
    LONG_NOMBREINTERNO = 60

    def asegura_camposdinamicos(modeloconrf, _current_usuario_id)
      if modeloconrf.nil? || modeloconrf.respuestafor.nil? ||
          modeloconrf.respuestafor.formulario.nil?
        return
      end

      ci = modeloconrf.respuestafor.formulario.campo_ids
      cd = modeloconrf.respuestafor.valorcampo.map(&:campo_id)
      sobran = cd - ci
      borrar = modeloconrf.respuestafor.valorcampo.where(campo_id: sobran)
        .map(&:id)
      modeloconrf.respuestafor.valorcampo_ids -= borrar
      puts modeloconrf.respuestafor.valorcampo_ids
      faltan = ci - cd
      faltan.each do |f|
        vc = Mr519Gen::Valorcampo.new(
          respuestafor_id: modeloconrf.respuestafor_id,
          campo_id: f,
          valor: "",
        )
        vc.save!(validate: false)
      end
    end
    module_function :asegura_camposdinamicos

    def nombre_a_nombreinterno(nombre)
      ni = nombre.gsub(/[^A-Za-z0-9_]/, "_")
      ni = ni.downcase
      ni[0..(LONG_NOMBREINTERNO - 1)]
    end
    module_function :nombre_a_nombreinterno

    # resps es una serie de registros con asociación respuestafor a
    # Mr519::Respuestafor para un mismo formulario
    def analiza_respuestas(respuestafor_ids, titulo, consolidado, _menserr)
      resps = Mr519Gen::Respuestafor.where(id: respuestafor_ids)
      if resps.count == 0
        _menserr << "No hay encuestas respondidas"
        return false
      end
      titulo << "Resultados de encuesta: " +
        resps[0].formulario.nombre
      resps[0].formulario.campo.order(:id).each do |c|
        case c.tipo
        when Mr519Gen::ApplicationHelper::TEXTO,
          Mr519Gen::ApplicationHelper::TEXTOLARGO,
          Mr519Gen::ApplicationHelper::FECHA
          cons = ""
          sep = ""
          Mr519Gen::Valorcampo.where(campo_id: c.id)
            .where("respuestafor_id IN (#{resps.map(&:id).join(",")})")
            .each do |vc|
            if vc.valor && vc.valor.strip != ""
              cons += sep + vc.valor.to_s
              sep = ".<hr>".html_safe
            end
          end
        when Mr519Gen::ApplicationHelper::ENTERO,
          Mr519Gen::ApplicationHelper::FLOTANTE
          cons = Mr519Gen::Valorcampo.where(campo_id: c.id)
            .where("respuestafor_id IN (#{resps.map(&:id).join(",")})")
            .average("CASE
                             WHEN valor = '' THEN 0
                             ELSE CAST(valor AS NUMERIC)
                           END")
        when Mr519Gen::ApplicationHelper::BOOLEANO
          si = Mr519Gen::Valorcampo.where(campo_id: c.id)
            .where("respuestafor_id IN (#{resps.map(&:id).join(",")})")
            .where(valor: "t").count
          no = Mr519Gen::Valorcampo.where(campo_id: c.id)
            .where("valor <> 't'").count
          cons = "Si: #{si}.  No: #{no}"
        when Mr519Gen::ApplicationHelper::SSTABLABASICA
          ab = ::Ability.new
          tb = ab.tablasbasicas.select do |l|
            l[1] == c.tablabasica.singularize
          end
          cons = ""
          sep = ""
          cla = Ability.tb_clase(tb[0])
          col1 = cla.all
          col1 = col1.habilitados if col1.respond_to?(:habilitados)
          col1.each do |rb|
            cuenta = Mr519Gen::Valorcampo.where(campo_id: c.id)
              .where("respuestafor_id IN (#{resps.map(&:id).join(",")})")
              .where("valor = ?", rb.id.to_s).count
            cons += sep + "#{rb.nombre}: #{cuenta}"
            sep = "<br> ".html_safe
          end
          cuenta = Mr519Gen::Valorcampo.where(campo_id: c.id)
            .where("respuestafor_id IN (#{resps.map(&:id).join(",")})")
            .where("valor = '' OR valor IS NULL").count
          cons += sep + "No respondida: #{cuenta}" if cuenta > 0

        when Mr519Gen::ApplicationHelper::SELECCIONSIMPLE
          cons = ""
          sep = ""
          Mr519Gen::Opcioncs.where(campo_id: c.id).each do |op|
            cuenta = Mr519Gen::Valorcampo.where(campo_id: c.id)
              .where("respuestafor_id IN (#{resps.map(&:id).join(",")})")
              .where("valor = ?", op.id.to_s).count
            cons += sep + "#{op.nombre}: #{cuenta}"
            sep = "<br> ".html_safe
          end
          cuenta = Mr519Gen::Valorcampo.where(campo_id: c.id)
            .where("respuestafor_id IN (#{resps.map(&:id).join(",")})")
            .where("valor = '' OR valor IS NULL").count
          cons += sep + "No respondida: #{cuenta}" if cuenta > 0

        else
          puts "Tipo desconocido"
          cons = "Tipo desconocido"
        end
        consolidado << { pregunta: c.nombre, consolidado: cons } if c.tipo != Mr519Gen::ApplicationHelper::PRESENTATEXTO
      end
      true
    end
    module_function :analiza_respuestas

    # Dado un objeto que puede tener varios respuestafor  y un formulario_id
    # y un campo_id retorna el valor del campo en el formulario o nil
    def presenta_valor(objeto, formulario_id, campo_id)
      rf = objeto.respuestafor.find_by(formulario_id: formulario_id)
      return unless rf

      vc = rf.valorcampo.find_by(campo_id: campo_id)
      return unless vc

      vc.presenta_valor(false)
    end
    module_function :presenta_valor
  end
end

app/views/mr519_gen/encuestaspersona/_campo_fechacambio_localizada.html.erb
<% if can? :manage, Mr519Gen::Encuestausuario %>
  <%= f.input(:fechacambio,
    input_html:  {},
    as: :string) 
  %>
<% else %>
  <%= f.input(:fechacambio,
    input_html: { readonly: "readonly" })
  %>
<% end %>

app/views/mr519_gen/encuestaspersona/_campo_fechaini_localizada.html.erb
<% if can? :manage, Mr519Gen::Encuestausuario %>
  <%= f.input(:fechaini,
    input_html: {},
    as:  :string) 
  %>
<% else %>
  <%= f.input(:fechaini,
    input_html: { readonly: "readonly" }) 
  %>
<% end %>

app/views/mr519_gen/encuestaspersona/_campo_formulario_id.html.erb
<%= render partial: "encuestasusuario/campo_formulario_id" %>

app/views/mr519_gen/encuestaspersona/_externa_intro.html.erb
<% if @registro.respond_to?(:respuestafor) && 
    @registro.respuestafor.respond_to?(:formulario) &&
    @registro.respuestafor.formulario %>
  <h1><%= @registro.respuestafor.formulario.nombre %></h1>
<% else %>
  <h1>
    Error con aplicación de encuesta <%= @registro.id %>: 
    falta formulario en respuestafor
  </h1>
<% end %>
<p>
  <% if @registro.respond_to?(:persona) && @registro.persona %>
    Encuesta para <%= @registro.persona.presenta_nombre %>
  <% else %>
    Error con aplicación de encuesta <%= @registro.id %>: 
    no tiene persona
  <% end %>
</p>
<p>
  <% if @registro.respond_to?(:planencuesta) && @registro.planencuesta %>
    Por responder entre el 
    <%= @registro.planencuesta.fechaini_localizada %> 
    y el <%= @registro.planencuesta.fechafin_localizada %>
  <% else %>
    Error con aplicación de encuesta <%= @registro.id %>: 
    no tiene planencuesta
  <% end %>
</p>
<% if current_usuario && can?(:read, @registro) %>
  <p>
  <% if @registro.respond_to?(:fechainv) %>
    Encuesta enviada el <%= @registro.fechainv %> a <%= @registro.destcorreoinv %> con confirmación <%= @registro.evidenciacorreoinv %>
  <% else %>
    Encuesta no enviada por correo 
  <% end %>
  </p>
<% end %>
<p>
  <% if @registro.respuestafor.respond_to?(:fechacambio) %>
    Última edición el <%= @registro.respuestafor.fechacambio_localizada %>
  <% end %>
</p>

app/views/mr519_gen/encuestaspersona/_filtro_formulario.html.erb
<%= f.input(:busformulario,
  collection: Mr519Gen::Formulario.all,
  include_blank: true,
  input_html: {
    class: "tom-select",
    "data-action": "change->msip--enviarautomatico#enviar"
  },
  label: false,
  label_method: :presenta_nombre,
  selected: Msip::ModeloHelper.poromision(params, :busformulario),
  value_method: :id)
%>

app/views/mr519_gen/encuestaspersona/_index_acciones.html.erb
<% if can?(:edit, registro) %>
  <%= render partial: "boton_editar",
    locals: { registro: registro, mas_clases: "btn-sm" } %>
<% end %>
<%= render partial: "index_mas_acciones", locals: { f: f, registro: registro } %>
<% if can?(:destroy, registro) %>
  <%= render partial: "boton_eliminar",
    locals: { registro: registro, mas_clases: "btn-sm" } %>
<% end %>

app/views/mr519_gen/encuestaspersona/_show_campo_adurl.html.erb
<% if @registro && @registro.adurl %>
  <% e = encuestaexterna_url(@registro.adurl) %>
  <%= link_to e, e %>
<% end %>

app/views/mr519_gen/encuestaspersona/externa.html.erb
<%= simple_form_for @registro, 
    url: modelo_path(@registro),
    defaults: { input_html: { class: 'span10' } } do |f| 
%>
  <%= render partial: 'msip/hogar/errores', locals: { f: f } %> 
  
  <%= render partial: 'externa_intro', locals: { f: f } %> 
  
  <%= render partial: "mr519_gen/encuestasusuario/campo_respuestafor", 
    locals: { f: f } %> 
 
  <%= render partial: "externa_post", locals: { f: f } %> 

  <div class="form-actions">
    <%= f.button(:submit, 
      (f.object.new_record? ? "Responder" : 
       "Actualizar Repuesta"), 
       :class => "btn btn-sm btn-primary",
       "data-turbo" => false) %>
     <%= link_to t(".cancel", default: t("helpers.links.cancel")),
       modelos_path(@registro), 
class: "btn" 
     %>
  </div>
  
<% end %>

app/views/mr519_gen/encuestaspersona/gracias.html.erb
<h1>¡Gracias por responder la encuesta!</h1>
<p>Conozca más de Pasos de Jesús en <a href="https://pasosdeJesus.org">https://pasosdeJesus.org</a></p>
<p>Puede apoyarnos con donaciones o adquiriendo productos y servicios que ofrecemos</p>

app/views/mr519_gen/encuestaspersona/resultados.html.erb
<h1><%= @titulo %></h1>
<h2>Usuario que la respondieron: <%= @usuarios.count %></h2>
<table class="table table-striped">
  <tr>
    <th>Nombres y apellidos</th>
  </tr>
  <% @usuarios.each do |u| %>
    <tr><td><%= u.presenta_nombre %></td></tr>
  <% end %>
</table>

<h2>Consolidados</h2>
<table class="table table-striped">
  <tr>
    <th>Pregunta</th>
    <th>Consolidado</th>
  </tr>
  <% @consolidado.each do |c| %>
    <tr>
      <td><%= c[:pregunta] %></td>
      <td><%= c[:consolidado] %></td>
    </tr>
  <% end %>
</table>